//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Business.Util.Resources.CardExcMsg
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardExcMsg
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardExcMsg()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Business.Util.Resources.CardExcMsg.CardExcMsg", typeof(CardExcMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IdentifierCard é obrigatório.
        /// </summary>
        public static string EXC0001
        {
            get
            {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login obrigatório.
        /// </summary>
        public static string EXC0002
        {
            get
            {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF/CNPJ é obrigatório.
        /// </summary>
        public static string EXC0003
        {
            get
            {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PanLastDigits são obrigatórios.
        /// </summary>
        public static string EXC0004
        {
            get
            {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CardIdentifier inválido.
        /// </summary>
        public static string EXC0005
        {
            get
            {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountId é obrigatório.
        /// </summary>
        public static string EXC0006
        {
            get
            {
                return ResourceManager.GetString("EXC0006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do identificador do cartão não informado.
        /// </summary>
        public static string EXC0007
        {
            get
            {
                return ResourceManager.GetString("EXC0007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do pin não informado.
        /// </summary>
        public static string EXC0008
        {
            get
            {
                return ResourceManager.GetString("EXC0008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin informado é inválido.
        /// </summary>
        public static string EXC0009
        {
            get
            {
                return ResourceManager.GetString("EXC0009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de motivo não informada.
        /// </summary>
        public static string EXC0010
        {
            get
            {
                return ResourceManager.GetString("EXC0010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ConfirmationPin não informado.
        /// </summary>
        public static string EXC0011
        {
            get
            {
                return ResourceManager.GetString("EXC0011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campos Pin e ConfirmationPin diferentes.
        /// </summary>
        public static string EXC0012
        {
            get
            {
                return ResourceManager.GetString("EXC0012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status do cartão inválido.
        /// </summary>
        public static string EXC0013
        {
            get
            {
                return ResourceManager.GetString("EXC0013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nacionality é obrigatório.
        /// </summary>
        public static string EXC0014
        {
            get
            {
                return ResourceManager.GetString("EXC0014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campo de MotherName é obrigatório.
        /// </summary>
        public static string EXC0015
        {
            get
            {
                return ResourceManager.GetString("EXC0015", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender é obrigatório.
        /// </summary>
        public static string EXC0016
        {
            get
            {
                return ResourceManager.GetString("EXC0016", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name é obrigatório.
        /// </summary>
        public static string EXC0017
        {
            get
            {
                return ResourceManager.GetString("EXC0017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MaritalStatus é obrigatório.
        /// </summary>
        public static string EXC0018
        {
            get
            {
                return ResourceManager.GetString("EXC0018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CellPhone é obrigatório.
        /// </summary>
        public static string EXC0019
        {
            get
            {
                return ResourceManager.GetString("EXC0019", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório.
        /// </summary>
        public static string EXC0020
        {
            get
            {
                return ResourceManager.GetString("EXC0020", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta remetente não encontrada.
        /// </summary>
        public static string EXC0021
        {
            get
            {
                return ResourceManager.GetString("EXC0021", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não é permitido letras no campo Number do endereço.
        /// </summary>
        public static string EXC0022 {
            get {
                return ResourceManager.GetString("EXC0022", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logradouro é obrigatório.
        /// </summary>
        public static string EXC0023 {
            get {
                return ResourceManager.GetString("EXC0023", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bairro é obrigatório.
        /// </summary>
        public static string EXC0024 {
            get {
                return ResourceManager.GetString("EXC0024", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CEP é obrigatório.
        /// </summary>
        public static string EXC0025 {
            get {
                return ResourceManager.GetString("EXC0025", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatório.
        /// </summary>
        public static string EXC0026 {
            get {
                return ResourceManager.GetString("EXC0026", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório.
        /// </summary>
        public static string EXC0027 {
            get {
                return ResourceManager.GetString("EXC0027", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to País é obrigatório.
        /// </summary>
        public static string EXC0028 {
            get {
                return ResourceManager.GetString("EXC0028", resourceCulture);
            }
        }
    }
}