//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Business.Util.Resources.AccountExcMsg
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountExcMsg
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountExcMsg()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Business.Util.Resources.AccountExcMsg.AccountExcMsg", typeof(AccountExcMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login obrigatório.
        /// </summary>
        public static string EXC0001
        {
            get
            {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF/CNPJ é obrigatório.
        /// </summary>
        public static string EXC0002
        {
            get
            {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountId é obrigatório.
        /// </summary>
        public static string EXC0003
        {
            get
            {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StartDate é obrigatório.
        /// </summary>
        public static string EXC0004
        {
            get
            {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndDate é obrigatório.
        /// </summary>
        public static string EXC0005
        {
            get
            {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OperationType é obrigatório.
        /// </summary>
        public static string EXC0006
        {
            get
            {
                return ResourceManager.GetString("EXC0006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountName é obrigatório.
        /// </summary>
        public static string EXC0007
        {
            get
            {
                return ResourceManager.GetString("EXC0007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountType é obrigatório.
        /// </summary>
        public static string EXC0008
        {
            get
            {
                return ResourceManager.GetString("EXC0008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status é obrigatório.
        /// </summary>
        public static string EXC0009
        {
            get
            {
                return ResourceManager.GetString("EXC0009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserId é obrigatório.
        /// </summary>
        public static string EXC0010
        {
            get
            {
                return ResourceManager.GetString("EXC0010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountKey é obrigatório.
        /// </summary>
        public static string EXC0011
        {
            get
            {
                return ResourceManager.GetString("EXC0011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campo de data obrigatório.
        /// </summary>
        public static string EXC0012
        {
            get
            {
                return ResourceManager.GetString("EXC0012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Você não possui nenhuma conta ativa para esta Unidade de Negócio.
        /// </summary>
        public static string EXC0013
        {
            get
            {
                return ResourceManager.GetString("EXC0013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta não encontrada.
        /// </summary>
        public static string EXC0014
        {
            get
            {
                return ResourceManager.GetString("EXC0014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não é possível transferir para a conta que esta sendo utilizada.
        /// </summary>
        public static string EXC0015
        {
            get
            {
                return ResourceManager.GetString("EXC0015", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to UserId é obrigatório.
        /// </summary>
        public static string EXC0016
        {
            get
            {
                return ResourceManager.GetString("EXC0016", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to TaxId inválido.
        /// </summary>
        public static string EXC0017
        {
            get
            {
                return ResourceManager.GetString("EXC0017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CompanyId é obrigatório.
        /// </summary>
        public static string EXC0018
        {
            get
            {
                return ResourceManager.GetString("EXC0018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountOperationLimitType é obrigatório.
        /// </summary>
        public static string EXC0019
        {
            get
            {
                return ResourceManager.GetString("EXC0019", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountOperationLimitSubType é obrigatório.
        /// </summary>
        public static string EXC0020
        {
            get
            {
                return ResourceManager.GetString("EXC0020", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to MinLimitValue não pode ser negativo.
        /// </summary>
        public static string EXC0021
        {
            get
            {
                return ResourceManager.GetString("EXC0021", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MaxLimitValue não pode ser negativo.
        /// </summary>
        public static string EXC0022
        {
            get
            {
                return ResourceManager.GetString("EXC0022", resourceCulture);
            }
        }
    }
}