//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Auth.Util.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthMsg
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AuthMsg()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Auth.Util.Resources.AuthMsg", typeof(AuthMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nova senha de acesso
        /// </summary>
        public static string MSG0001
        {
            get
            {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prezado(a). Segue a sua nova senha de acesso ao aplicativo: {0}
        /// </summary>
        public static string MSG0002
        {
            get
            {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token de autorização
        /// </summary>
        public static string MSG0003
        {
            get
            {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token gerado: {0}
        /// </summary>
        public static string MSG0004
        {
            get
            {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seu acesso ao aplicativo foi criado com sucesso, agora você pode aproveitar todos os recursos disponíveis.
        /// </summary>
        public static string MSG0005
        {
            get
            {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seu acesso ao aplicativo foi criado com sucesso, agora você pode aproveitar todos os recursos disponíveis. Sua senha temporária para acesso a plataforma é {0}.
        /// </summary>
        public static string MSG0006
        {
            get
            {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
    }
}


