name: fitbank_450
description: A new Flutter project.

publish_to: "none"

version: 1.4.1+18

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.4.0
  jaguar_jwt: ^3.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  share_plus: ^3.0.4
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
