//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Business.Util.Resources.TaxPaymentExcMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaxPaymentExcMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaxPaymentExcMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Business.Util.Resources.TaxPaymentExcMsg.TaxPaymentExcMsg", typeof(TaxPaymentExcMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF/CNPJ é obrigatório.
        /// </summary>
        public static string EXC0001 {
            get {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF do contribuinte é obrigatório.
        /// </summary>
        public static string EXC0002 {
            get {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Principal inválido.
        /// </summary>
        public static string EXC0003 {
            get {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da revenda é obrigatório.
        /// </summary>
        public static string EXC0004 {
            get {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de barras inválido.
        /// </summary>
        public static string EXC0005 {
            get {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de conectividade social ou Digito inválido.
        /// </summary>
        public static string EXC0006 {
            get {
                return ResourceManager.GetString("EXC0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de pagamento inválida.
        /// </summary>
        public static string EXC0007 {
            get {
                return ResourceManager.GetString("EXC0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de referência Inválido.
        /// </summary>
        public static string EXC0008 {
            get {
                return ResourceManager.GetString("EXC0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total é obrigatório.
        /// </summary>
        public static string EXC0009 {
            get {
                return ResourceManager.GetString("EXC0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de vencimento inválida.
        /// </summary>
        public static string EXC0010 {
            get {
                return ResourceManager.GetString("EXC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro estadual é obrigatório.
        /// </summary>
        public static string EXC0011 {
            get {
                return ResourceManager.GetString("EXC0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido para Tipo de GARE.
        /// </summary>
        public static string EXC0012 {
            get {
                return ResourceManager.GetString("EXC0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta remetente não encontrada.
        /// </summary>
        public static string EXC0013 {
            get {
                return ResourceManager.GetString("EXC0013", resourceCulture);
            }
        }
    }
}
