export enum TaxPaymentRoutes {
  otherPayment = '/taxPayment',

  paymentDarj = '/taxpayment/darj',
  paymentDarjCodeNumber = '/taxPayment/darj/code',
  paymentDarjValues = '/taxPayment/darj/values',
  paymentDarjType = '/taxPayment/darj/type',
  paymentDarjDueDate = '/taxPayment/darj/dueDate',
  paymentDarjDescription = '/taxPayment/darj/description',
  paymentDarjConclude = '/taxPayment/darj/conclude',
  paymentDarjSummary = '/taxPayment/darj/summary',

  paymentGare = '/taxpayment/gare',
  paymentGareCodeNumber = '/taxPayment/gare/code',
  paymentGareValues = '/taxPayment/gare/values',
  paymentGareType = '/taxPayment/gare/type',
  paymentGareDueDate = '/taxPayment/gare/dueDate',
  paymentGareDescription = '/taxPayment/gare/description',
  paymentGareConclude = '/taxPayment/gare/conclude',
  paymentGareSummary = '/taxPayment/gare/summary',

  paymentFgts = '/taxpayment/fgts',
  paymentFgtsCodeRevenue = '/taxPayment/fgts/code',
  paymentFgtsValues = '/taxPayment/fgts/values',
  paymentFgtsIdentifier = '/taxPayment/fgts/identifier',
  paymentFgtsBarCode = '/taxPayment/fgts/barcode',
  paymentFgtsDate = '/taxPayment/fgts/Date',
  paymentFgtsDescription = '/taxPayment/fgts/description',
  paymentFgtsConclude = '/taxPayment/fgts/conclude',
  paymentFgtsSummary = '/taxPayment/fgts/summary',
}
