//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Business.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PushNotificationMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushNotificationMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Business.Util.Resources.PushNotificationMsg", typeof(PushNotificationMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferência.
        /// </summary>
        public static string MSG_TITLE_0001 {
            get {
                return ResourceManager.GetString("MSG_TITLE_0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Transferência no valor de R${0} foi realizada com sucesso!.
        /// </summary>
        public static string MSG_SUCCESS_0001 {
            get {
                return ResourceManager.GetString("MSG_SUCCESS_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a transferência de valor R${0}.
        /// </summary>
        public static string MSG_ERROR_0001 {
            get {
                return ResourceManager.GetString("MSG_ERROR_0001", resourceCulture);
            }
        }    

        /// <summary>
        ///   Looks up a localized string similar to Boleto.
        /// </summary>
        public static string MSG_TITLE_0002 {
            get {
                return ResourceManager.GetString("MSG_TITLE_0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O pagamento do boleto no valor de R${0} foi realizado com sucesso!.
        /// </summary>
        public static string MSG_SUCCESS_0002 {
            get {
                return ResourceManager.GetString("MSG_SUCCESS_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o pagamento do boleto de valor R${0}.
        /// </summary>
        public static string MSG_ERROR_0002 {
            get {
                return ResourceManager.GetString("MSG_ERROR_0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recarga.
        /// </summary>
        public static string MSG_TITLE_0003 {
            get {
                return ResourceManager.GetString("MSG_TITLE_0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A recarga de R${0} foi realizada com sucesso!.
        /// </summary>
        public static string MSG_SUCCESS_0003 {
            get {
                return ResourceManager.GetString("MSG_SUCCESS_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a recarga de R${0}.
        /// </summary>
        public static string MSG_ERROR_0003 {
            get {
                return ResourceManager.GetString("MSG_ERROR_0003", resourceCulture);
            }
        }   
    }
}
