//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Api.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiInfoMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiInfoMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Api.Common.Resources.ApiInfoMsg", typeof(ApiInfoMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleto encontrado.
        /// </summary>
        public static string ApiInfo0001 {
            get {
                return ResourceManager.GetString("ApiInfo0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token gerado.
        /// </summary>
        public static string ApiInfo0002 {
            get {
                return ResourceManager.GetString("ApiInfo0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais encontradas.
        /// </summary>
        public static string ApiInfo0003 {
            get {
                return ResourceManager.GetString("ApiInfo0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário autenticado.
        /// </summary>
        public static string ApiInfo0004 {
            get {
                return ResourceManager.GetString("ApiInfo0004", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Token válido.
        /// </summary>
        public static string ApiInfo0005 {
            get {
                return ResourceManager.GetString("ApiInfo0005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pagamento registrado com sucesso.
        /// </summary>
        public static string ApiInfo0006 {
            get {
                return ResourceManager.GetString("ApiInfo0006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favored salvo com sucesso.
        /// </summary>
        public static string ApiInfo0007 {
            get {
                return ResourceManager.GetString("ApiInfo0007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bloqueio de cartão solicitado com sucesso.
        /// </summary>
        public static string ApiInfo0008 {
            get {
                return ResourceManager.GetString("ApiInfo0008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transferência Pix registrada com sucesso.
        /// </summary>
        public static string ApiInfo0009 {
            get {
                return ResourceManager.GetString("ApiInfo0009", resourceCulture);
            }
        }
    }
}
