export enum UiFunction {
  account = 1,
  internalTransfer,
  moneyTransfer,
  boletoPayment,
  generateQrCode,
  readQrCode,
  smsOnboarding,
  findCardList,
  findCard,
  changePinCard,
  blockAndUnblockCard,
  contactlessCard,
  cancelCard,
  topUp,
  user,
  cardOnboarding,
  futureTransactions,
  pix,
  digitalWithdrawal,
}
